apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loadtool.yaml
configMapGenerator:
  - name: loadtool-cfg
    files:
      - loadtool.json
  - name: loadtool-target-nodes-cfg
    files:
      - static-nodes.json
