apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ethnode
spec:
  template:
    spec:
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: genesis
                items:
                  - key: genesis.json
                    path: genesis.json
            - configMap:
                name: ethnode-cfg
                items:
                  - key: static-nodes.json
                    path: static-nodes.json
            - secret:
                name: ethnodekey-
                items:
                  - key: key
                    path: nodekey
