name: Build and publish bbench image
on:
 release:
   ['published']
   
jobs:
  build-and-publish-images:
    name: Build and publish bbench image
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: yewnorosen
          password: ${{ secrets.YEWNOROSEN_DOCKERHUB_PUSH }}
      -
        name: checkout main
        uses: actions/checkout@v2
        with:
          path: main
      -
        name: Extract tags, labels for image
        id: bbench-meta
        uses: docker/metadata-action@v3
        with:
          images: yewnorosen/bbench
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Build and push bbench
        uses: docker/build-push-action@v2
        with:
          context: main
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.bbench-meta.outputs.tags }}
          labels: ${{ steps.bbench-meta.outputs.labels }}
      -
        name: Extract tags, labels for image
        id: loadtool-meta
        uses: docker/metadata-action@v3
        with:
          images: yewnorosen/bbench-loadtool
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Build and push bbench-loadtool
        uses: docker/build-push-action@v2
        with:
          context: main
          file: main/Dockerfile-loadtool
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.loadtool-meta.outputs.tags }}
          labels: ${{ steps.loadtool-meta.outputs.labels }}

  generate-sboms:
    name: Generate SBOMs
    needs: build-and-publish-images
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: yewnorosen/bbench:main
          format: cyclonedx
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: yewnorosen/bbench-loadtool:main
          format: cyclonedx

  publish-sbom:
    name: Publish SBOM to RKVST
    needs: generate-sboms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: leflambeur/rkvst-sbom@v0.0.2
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          command: release
          asset_id: assets/fa8dc0a4-1136-4f65-b4db-946ea8ffde47
          attachments: '["yewnorosen-bbench_latest.cyclonedx/yewnorosen-bbench_latest.cyclonedx"]'
      - uses: leflambeur/rkvst-sbom@v0.0.2
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          command: release
          asset_id: assets/cb3a1190-34b3-4ecc-9228-95138b2747bf
          attachments: '["yewnorosen-bbench-loadtool_latest.cyclonedx/yewnorosen-bbench-loadtool_latest.cyclonedx"]'
      
